services:

  kafka:
    image: apache/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_MESSAGE_MAX_BYTES: 104857600
      KAFKA_REPLICA_FETCH_MAX_BYTES: 104857600
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600

  app:
    image: ru.otus.crowd.proj.docs.be/crowd-proj-docs-cards-app-kafka:0.0.1
    depends_on:
      - kafka
    links:
      - kafka
    environment:
      KAFKA_HOSTS: kafka:19092
      KAFKA_TOPIC_IN_V1: marketplace-doc-card-v1-in
      KAFKA_TOPIC_OUT_V1: marketplace-doc-card-v1-out
      KAFKA_TOPIC_IN_V2: marketplace-doc-card-v2-in
      KAFKA_TOPIC_OUT_V2: marketplace-doc-card-v2-out
      KAFKA_PRODUCER_MAX_REQUEST_SIZE: 10485760
      KAFKA_CONSUMER_FETCH_MAX_BYTES: 10485760

#services:
#  kafka:
#    image: apache/kafka:latest
#    hostname: kafka
#    container_name: kafka
#    ports:
#      - '9092:9092'
#    environment:
#      KAFKA_NODE_ID: 1
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
#      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:19092'
#      KAFKA_PROCESS_ROLES: 'broker,controller'
#      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
#      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
#      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
#      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
#      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
#      KAFKA_MESSAGE_MAX_BYTES: 104857600  # Max size of a single message (100 MB)
#      KAFKA_REPLICA_FETCH_MAX_BYTES: 104857600  # Max fetch size for replicas (100 MB)
#      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600  # Max size of a single request (100 MB)
#
#
#  app:
#    image: ru.otus.crowd.proj.docs.be/crowd-proj-docs-cards-app-kafka:0.0.1
#    depends_on:
#      - kafka
#    links:
#      - kafka
#    environment:
#      KAFKA_HOSTS: kafka:19092
#      KAFKA_TOPIC_IN_V1: marketplace-doc-card-v1-in
#      KAFKA_TOPIC_OUT_V1: marketplace-doc-card-v1-out
#      KAFKA_TOPIC_IN_V2: marketplace-doc-card-v2-in
#      KAFKA_TOPIC_OUT_V2: marketplace-doc-card-v2-out
#      KAFKA_PRODUCER_MAX_REQUEST_SIZE: 10485760  # 10 MB
#      KAFKA_CONSUMER_FETCH_MAX_BYTES: 10485760  # 10 MB

